config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :tasks
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      flash[:success] = 'Task successfully created'
      redirect_to @task
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = 'Task was successfully updated'
      redirect_to @task
    else
      flash[:error] = 'Something went wrong'
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      flash[:success] = 'Task was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to @task
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css", :rel => "stylesheet"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsTaskManagerWithHaml
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/tasks/edit.html.haml
.container
  %h1 Add a new task
  .content
    = simple_form_for(@task) do |f|
      = f.input :title
      = f.input :details
      = f.input :completed
      = f.button :submit, 'Update task', class: 'btn'
      = link_to "Back", tasks_path, class: 'btn'

app/views/tasks/index.html.haml
.container
  %h1 My tasks
  %dl
    - @tasks.each do |task|
      %dt
        - if task.completed
          %i.fas.fa-check-square
        - else
          %i.fas.fa-square
        = link_to task.title, task_path(task)
        = link_to task_path(task), method: :delete, data: { confirm: "Are you sure?" } do
          %i.fas.fa-trash


  = link_to 'New task', new_task_path, class: 'btn'

app/views/tasks/new.html.haml
.container
  %h1 Add a new task
  .content
    = simple_form_for(@task) do |f|
      = f.input :title
      = f.input :details
      = f.button :submit, 'Add task', class: 'btn-back'
      = link_to "Back", tasks_path, class: 'btn-back'

app/views/tasks/show.html.haml
.container
  %h1=@task.title
  .content
    %p=@task.details
    - if @task.completed
      %i.fas.fa-check-square
    - else
      %i.fas.fa-square
    Completed
    %hr
    = link_to 'Edit task', edit_task_path(@task), class: 'btn'
    = link_to 'Back', tasks_path, class: 'btn'